# Generated by Django 6.0 on 2026-02-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='share_location',
            field=models.URLField(blank=True, help_text='Google Maps location URL', null=True),
        ),
    ]
