# Generated by Django 6.0 on 2026-01-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_mattress_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beddingproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/bedding/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/categories/'),
        ),
        migrations.AlterField(
            model_name='customfurniture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/custom-furniture/'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/furniture/'),
        ),
        migrations.AlterField(
            model_name='heavydutyproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/heavy-duty/'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/mattresses/'),
        ),
        migrations.AlterField(
            model_name='newarrival',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/new-arrivals/'),
        ),
        migrations.AlterField(
            model_name='specialproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/special/'),
        ),
    ]
