# Generated by Django 6.0 on 2026-01-20 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brand_alter_furniture_brand_alter_mattress_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furniture', to='products.category'),
        ),
    ]
