# Generated by Django 6.0 on 2026-01-20 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_furniture_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeddingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/bedding-categories/')),
            ],
            options={
                'verbose_name_plural': 'Bedding Categories',
            },
        ),
        migrations.CreateModel(
            name='FurnitureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/furniture-categories/')),
            ],
            options={
                'verbose_name_plural': 'Furniture Categories',
            },
        ),
        migrations.CreateModel(
            name='MattressCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/mattress-categories/')),
            ],
            options={
                'verbose_name_plural': 'Mattress Categories',
            },
        ),
        migrations.AlterField(
            model_name='beddingproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bedding_products', to='products.beddingcategory'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furniture', to='products.furniturecategory'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mattresses', to='products.mattresscategory'),
        ),
    ]
