# Generated by Django 6.0 on 2026-01-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_beddingcategory_furniturecategory_mattresscategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='NewArrival',
        ),
    ]
