# Generated by Django 6.0 on 2026-01-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_category_delete_newarrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mattress',
            name='sizes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
