# Generated by Django 6.0 on 2026-01-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_sofacategory_sofa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sofa',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='sofa',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='sofa',
            name='pricing_info',
            field=models.CharField(default='Contact Salesman', help_text='Pricing information', max_length=100),
        ),
    ]
