# Generated by Django 6.0 on 2026-01-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_sofa_base_price_remove_sofa_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/interior-applications/')),
            ],
            options={
                'verbose_name_plural': 'Interior Applications',
            },
        ),
        migrations.DeleteModel(
            name='HeavyDutyProduct',
        ),
    ]
