# Generated by Django 6.0 on 2026-01-23 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_heavyduty_to_interiorapplication'),
    ]

    operations = [
        # Rename SpecialProduct to HomeUtility in Python code only - table stays the same
        migrations.RenameModel(
            old_name='SpecialProduct',
            new_name='HomeUtility',
        ),
        migrations.AlterModelOptions(
            name='homeutility',
            options={'verbose_name_plural': 'Home Utilities'},
        ),
    ]
