# Generated by Django 6.0 on 2026-01-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_homeutility_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeutility',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='homeutility',
            name='description',
        ),
        migrations.AddField(
            model_name='homeutility',
            name='sizes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='homeutility',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/home-utilities/'),
        ),
    ]
