# Generated by Django 6.0 on 2026-01-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_homeutility_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beddingproduct',
            name='original_price',
        ),
    ]
