# Generated by Django 6.0 on 2026-01-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_beddingproduct_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfurniture',
            name='icon',
        ),
    ]
