# Generated by Django 6.0 on 2026-01-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_customfurniture_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='furniture_type',
            field=models.CharField(blank=True, choices=[('Cots', 'Cots'), ('Sofa', 'Sofa'), ('Desk', 'Desk'), ('Wardrobe', 'Wardrobe'), ('Bed', 'Bed'), ('Chair', 'Chair'), ('Table', 'Table'), ('Cabinet', 'Cabinet'), ('Shelf', 'Shelf'), ('Bench', 'Bench')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='room',
            field=models.CharField(blank=True, choices=[('Living Room', 'Living Room'), ('Bedroom', 'Bedroom'), ('Kitchen', 'Kitchen'), ('Office', 'Office'), ('Dining Room', 'Dining Room'), ('Bathroom', 'Bathroom'), ('Home Office', 'Home Office'), ('Outdoor', 'Outdoor')], max_length=100, null=True),
        ),
    ]
