# Generated by Django 6.0 on 2026-01-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_furniture_furniture_type_alter_furniture_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='description',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='room',
        ),
    ]
