# Generated by Django 6.0 on 2026-02-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_furniture_badge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_photo', models.ImageField(blank=True, null=True, upload_to='products/testimonials/')),
                ('review', models.TextField()),
                ('star_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('product_photo', models.ImageField(blank=True, null=True, upload_to='products/testimonials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='mattress',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='mattress',
            name='discount_percent',
        ),
        migrations.AlterField(
            model_name='mattress',
            name='sizes',
            field=models.JSONField(blank=True, default=list, help_text='JSON format: [{"category": "Single", "dimensions": [{"size": "72 x 36", "price": 13500, "original_price": 18000}]}, ...]', null=True),
        ),
    ]
