# Generated by Django 6.0 on 2026-02-08 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_testimonial_remove_mattress_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrthopaedicMattress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/orthopaedic-mattresses/')),
                ('sizes', models.JSONField(blank=True, default=list, help_text='JSON format: [{"category": "Single", "dimensions": [{"size": "72 x 36", "price": 13500, "original_price": 18000}]}, ...]', null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('doctor_recommended', models.BooleanField(default=True, help_text='Doctor recommended orthopaedic mattress')),
                ('featured', models.BooleanField(default=False, help_text='Feature as prime product')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orthopaedic_mattresses', to='products.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orthopaedic_mattresses', to='products.mattresscategory')),
            ],
            options={
                'verbose_name_plural': 'Orthopaedic Mattresses',
            },
        ),
    ]
