# Generated by Django 6.0 on 2026-02-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_orthopaedicmattress'),
    ]

    operations = [
        migrations.AddField(
            model_name='beddingproduct',
            name='sizes',
            field=models.JSONField(blank=True, default=list, help_text='JSON format: [{"category": "Single", "dimensions": [{"size": "72 x 36", "price": 13500, "original_price": 18000}]}, ...]', null=True),
        ),
    ]
