# Generated by Django 6.0 on 2026-03-07 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_beddingproduct_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MattressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/mattresses/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('mattress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.mattress')),
            ],
            options={
                'verbose_name': 'Mattress Image',
                'verbose_name_plural': 'Mattress Images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
